name: 'Mary Beth Dennie, Lpc'
favicon: null
layout_spectrum: 0.4991648616269231
typography_spectrum: 0.192359724547714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9926704668905586
  lightness: 0.9393561182077974
  saturation: 0.9519542576745152
  rhythmicContrast: 0.2455964160617441
purpose: []
