name: 'Mary Beth Dennie, Lpc'
favicon: null
layout_spectrum: 0.55524
typography_spectrum: 0.27399
title: 'Mary Beth Dennie, Licensed Professional Counselor'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07081d'
    - '#fbf885'
    - '#06307c'
    - '#fcc47c'
    - '#1f6e8d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
