name: 'Mary Beth Dennie, Lpc'
favicon: null
layout_spectrum: 0.25967
typography_spectrum: 0.62023
title: Welcome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07081d'
    - '#fbf885'
    - '#06307c'
    - '#fcc47c'
    - '#1f6e8d'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
